### ISSUE TITLE
Page links are not working

### ISSUE THREAD

**Issue by eliseomartelli** [NalinPlad/hkkr.in#4]
Kudos on the client but I wanted you to know that page links are not working.

Example:

```
hkkr.in/32773517
```

Brings me to this repo

**Comment by NalinPlad** [comment]
👀 good catch, I made a lot of changes to the project recently and forgot to test that lol, let me check it out

**Comment by NalinPlad** [comment]
Alright fixed. It was a problem with the fact that I didn't check if the query had an ID as a parameter before redirecting
