### ISSUE TITLE
Modern terminal support URLs

### ISSUE THREAD

**Issue by gabrielsroka** [NalinPlad/hkkr.in#8]
```js
function link(url, text) {
    return `\x1b]8;;${url}\x1b\\${text}\x1b]8;;\x1b\\`;
}
```

**Comment by NalinPlad** [comment]
looks interesting, I didn't know about this until now. I think I will implement this on the title while also leaving the URL for supporting other terminal emulators.

**Comment by NalinPlad** [comment]
Added with 0911e70
